### ISSUE TITLE
got ImportError when import ksuid

### ISSUE THREAD

**Issue by subcrew** [saresend/KSUID#1]
```
$ sudo -H pip install ksuid                                                                                                                                                   
Collecting ksuid
Installing collected packages: ksuid
Successfully installed ksuid-1.3
$ python                                                                                                                                                                    
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ksuid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ksuid/__init__.py", line 6, in <module>
    from ksuid.ksuid import *
ImportError: No module named ksuid
>>> 
```

**Comment by rskumar** [comment]
I too am getting this issue. Is this failing for Python 2.7.x?
